version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    container_name: shortenme_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  # web:
  #   build: .
  #   container_name: shortenme_web
  #   depends_on:
  #     - db
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}
  #     NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
  #   volumes:
  #     - .:/app
  #   command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run build && npm run start"

volumes:
  pgdata:
